# Generated by Django 5.0.4 on 2024-04-07 16:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingCounter', '0003_alter_bill_billnumber_alter_bill_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='billNumber',
            field=models.CharField(default=uuid.UUID('3a805897-0efa-4ced-8c0f-9ded87d3440e'), max_length=200),
        ),
    ]
