# Generated by Django 5.0.4 on 2024-04-08 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingCounter', '0005_rename_order_orderedproduct_alter_bill_billnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billNumber',
            field=models.CharField(default=uuid.UUID('03aa3606-6c6b-4f0a-9b12-ceac203a6529'), max_length=200),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
