# Generated by Django 5.0.4 on 2024-04-09 03:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingCounter', '0006_alter_bill_billnumber_alter_orderedproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billNumber',
            field=models.CharField(default=uuid.UUID('15cded29-b255-4e2a-90af-74777e18fa17'), max_length=200),
        ),
    ]
